#!/bin/sh
# Logger for dispatch-frontend. Reads stdout from dispatch-frontend-srv and
# writes to /var/log/dispatch-frontend/ using s6-log.

exec /usr/bin/s6-setuidgid tradam \
    /usr/bin/s6-log -b -d3 -- n10 s10000000 T /var/log/dispatch-frontend
